In [1]:
#pro_1

import math
C,H=50,30
strg=input(print("enter values for D : "))
lst=strg.split(',')
result=[]
for i in lst:
    Q=math.floor(math.sqrt((2*C*int(i))/H))
    result.append(Q)
for i in result:
    print(i)
    

enter values for D : 
None100,150,180
18
22
24


In [4]:
#prog_2

import numpy
i=int(input("enter no of rows : "))
j=int(input("enter no of columns : "))

matrix = numpy.ndarray(shape=(i,j),dtype=int)

for m in range(i):
    for n in range(j):
        matrix[m][n] = m*n

print(matrix)


enter no of rows : 3
enter no of columns : 5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [21]:
# prog_3

mystr = input("enter comma seperated string : ")

lst=mystr.split(',')

lst.sort()              

print(lst)



enter comma seperated string : without,hello,bag,world
['bag', 'hello', 'without', 'world']


In [22]:
# prog_4

mystr1 = input("enter space seperated string : ")

lst1=mystr1.split(' ')

rs=list(set(lst1))

print(rs)




enter space seperated string : hello world and pactice makes perfect and hello world again
['perfect', 'again', 'hello', 'pactice', 'world', 'makes', 'and']


In [15]:
# prog_5

mystr2 = input("enter string : ")

letters=0
digits=0
for s in mystr2:
    if s.isdigit():
        
        digits+=1
    elif s.isalpha():
        
        letters+=1
        
    else:
        pass

print("letters = {} \ndigits = {}".format(letters,digits))

enter string : hello world! 123
letters = 10 
digits = 3
